=== joshmoore/sptx-format/schema/field_of_view/field_of_view.json
{
  "$id": "https://github.com/spacetx/sptx-format/schema/field_of_view/field_of_view.json",
  "type": "object",
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "required": [
    "version",
    "dimensions",
    "shape",
    "fov",
    "tiles"
  ],
  "additionalProperties": false,
  "properties": {
    "version": {
      "$ref": "schema/version.json"
    },
    "extras": {
      "$id": "/properties/extras",
      "description": "unstructured field used to contain additional data about this data manifest",
      "default": null,
      "examples": [
        null, "spaceTx is great", {"extra_metadata": "critical_info"}
      ]
    },
    "dimensions": {
      "$id": "/properties/dimensions",
      "type": "array",
      "description": "dimensions of the image tensor described by this fov specification",
      "minItems": 1,
      "items": {
        "$id": "/properties/dimensions/items",
        "type": "string",
        "title": "Dimensions schema",
        "description": "a dimension of the tensor described by this fov specification",
        "examples": [
          "x",
          "y",
          "c",
          "z",
          "r"
        ]
      }
    },
    "shape": {
      "$id": "/properties/shape",
      "type": "object",
      "required": [
        "c", "z"
      ],
      "properties": {
        "r": {
          "$id": "/properties/shape/properties/r",
          "description": "Number of imaging rounds",
          "type": "integer",
          "default": 1,
          "examples": [
            1, 2, 10
          ],
          "minimum": 1
        },
        "c": {
          "$id": "/properties/shape/properties/c",
          "type": "integer",
          "description": "Number of channels",
          "default": 1,
          "examples": [
            3, 5, 10
          ],
          "minimum": 1
        },
        "z": {
          "$id": "/properties/shape/properties/z",
          "type": "integer",
          "title": "Number of z-sections",
          "default": 1,
          "examples": [
            1, 34, 67
          ],
          "minimum": 1
        }
      }
    },
    "fov": {
      "$id": "/properties/fov",
      "type": "integer",
      "minimum": 0,
      "description": "identifies the index of this field of view within a larger experiment",
      "examples": [
        0, 1, 4
      ]
    },
    "tiles": {
      "minItems": 1,
      "items": {
        "$ref": "schema/field_of_view/tiles/tiles.json"
      }
    },
    "default_tile_shape": {
      "$id": "/properties/default_tile_shape",
      "type": "array",
      "minItems": 2,
      "maxItems": 2,
      "items": {
        "$id": "/properties/default_tile_shape/items",
        "type": "integer",
        "description": "the default tile shape (x, y) of the tiles in this field of view.",
        "example": 2048,
        "minimum": 0
      }
    },
    "default_tile_format": {
      "$id": "/properties/default_tile_format",
      "type": "string",
      "title": "The default tile format for this field of view.",
      "examples": [
        "TIFF",
        "NPY"
      ]
    }
  }
}

=== joshmoore/sptx-format/examples/field_of_view/positive/field_of_view.json
{
  "version": "0.0.0",
  "fov": 0,
  "dimensions": [
      "x",
      "y",
      "z",
      "r",
      "c"
  ],
  "shape": {
      "z": 45,
      "r": 8,
      "c": 2
  },
  "default_tile_format": "TIFF",
  "default_tile_shape": [
    2048,
    2048
  ],
  "extras": "nothing to see here",
  "tiles": [
    {
      "coordinates": {
        "x": [0.0, 0.1],
        "y": [0.0, 0.1],
        "z": [0.0]
      },
      "indices": {
        "z": 0,
        "r": 0,
        "c": 0
      },
      "file": "fdaj3902.tiff",
      "tile_format": "TIFF",
      "sha256": "64f19dfc6d37dab41f122da95d973245e21493c710",
      "extras": {
        "are_we_missing_something":"probably"
      }
    },
    {
      "coordinates": {
        "x": [0.0, 0.1],
        "y": [0.0, 0.1],
        "z": [0.1]
      },
      "indices": {
        "z": 1,
        "r": 1,
        "c": 0
      },
      "file": "F_1_Z_1_H_1_C_0.tiff",
      "tile_format": "TIFF",
 	  "sha256": "da95d973245e21493c71091adcdf9321d5c5fad0b5",
      "extras": {
        "are_we_missing_something": "probably"
      }
    }
  ]
}
